### PR TITLE
#16 Fix memory leaks

### PR DESCRIPTION
**Pull request by Lecrapouille**

### CODE REVIEW

**Comment by Lecrapouille** [comment]
I called valgrind on Zipper-test. Could be better to add more unit tests to check if really everything is correct. You should also compile with address sanitizer to verify (I did not because I do not know CMake syntax).

**Comment by Lecrapouille** [comment]
@oranja Do you think so ? :) I would be agree with you concerning a pure C++ code but here C++ wraps C code which initially called malloc. So, on the original code, at the end, tries to call free deeper in the lib on something new'ed and that is something that valgrind was yelling at. I followed the C way. I tried new/delete without success. Maybe I'm wrong so feel free to modify my code.

I have no more leaks with the given unit tests but I still suspect more leaks not covered here. Fix will be for next time.

**Comment by oranja** [comment]
Maybe I was too quick to make that judgement. I know it's a complicated integration between the C and C++ code. I'll have to look again to see what's really going on there, but I trust you if you say that you've given it some thought and that's the most reasonable way.

**Comment by Lecrapouille** [comment]
No worries that's why we're code reviewing :)

**Comment by Lecrapouille** [comment]
PS: I just reworked my patch to fix possible memory leaks when throwing exception from the constructor. This case is not covered by zipper unit tests. Example `zipper::Unzipper zip("thisfiledoesnotexist");`

**Pull request merged**
