### PR TITLE
further changes to make zipper compatible for additional systems

### PR DESCRIPTION
**Pull request by fbergmann**
I'm not actually sure you want to merge this back, but i thought i let you know. I needed the api to compile on systems that are not yet capable of running c++11. In any case, please have  a look and see what works for you.

### CODE REVIEW

**Comment by sebastiandev** [comment]
Hey there... well.. i not sure about this. Do you know other people that might benefit from this? Someone interested on the library that cannot use c++11 yet?

I kinda like the simplicity that c++11 offered to make the code smaller, clearer and elegant so to speak.

I'll leave this open a couple of days.

**Comment by fbergmann** [comment]
Like I said before I'm not sure either the feedback I received so far is that the dependency on the c++17 STL or boost would be too cumbersome. So I might have to even reimplement the filesystem bits in plain c.i can understand if that is not the direction you want to take this.

**Comment by sebastiandev** [comment]
Hey there, im back a little late, but finally back. It looks like theres a conflict with the tools source?
if thats resolved i guess we can merge everything

**Comment by fbergmann** [comment]
so what changed between now and then, was that i removed all the dependency on the different file system api's in favor of taking the one from our project, where we encapsulated everything before. I think starting from my version and using your 

https://github.com/sebastiandev/zipper/commit/133829bd039ed7c6daedf959b2c968e99fdaab17

it should work fine again

**Pull request merged**
