### PR TITLE
Add basic error_code handeling to unzipper

### PR DESCRIPTION
**Pull request by Togtja**
Here is an example that should help with #88 
I do not remove exeption to keep compatibility with the old API, similar to what can be found in `std::filesystem`

### CODE REVIEW

**Comment by Lecrapouille** [comment]
@Togtja Is this still in draft ? Do you want to be merged in dev branch ?

**Comment by Togtja** [comment]
I think there are more places where the an exception is thrown where I have not gotten to.
So as is now it will add replacements for exceptions for the Unzipper class, but I have not done this for other places (Zipper class).
I might get some time to look at it at some point, but atm I am quite busy, so anybody feel free to continue, doing something similar to the Zipper class.

**Comment by Neustradamus** [comment]
@Togtja: Have you any progress/news about your PR?

**Comment by Togtja** [comment]
> @Togtja: Have you any progress/news about your PR?

@Neustradamus I haven't worked on it, a mixture of forgetting and time. I might get to look at it, but no promises

**Comment by Lecrapouille** [comment]
Closing since I'm currently working on it. See https://github.com/sebastiandev/zipper/issues/88

**Pull request closed without merging**
