### PR TITLE
Add continuous integration: Travis and appVeyor

### PR DESCRIPTION
**Pull request by Lecrapouille**
Add scripts for continuous integration:
* Travis: gcc and clang for Linux 17.04 and OS X.
* appVeyor: MinGW: not yet ok (cmake fails locating zlib)
Note: tested for 64-bits architectures.

### CODE REVIEW

**Comment by Lecrapouille** [comment]
I'm not a good writer on CI so consider this commit has a working prototype. Since issue #16 I added valgrind to unit-tests (I reworked my initial PR) :
* for Linux and OS X (for this last, because of too many jobs in Travis server, they halted the process, so I'm not sure OS X passed with Valgrind, will see tomorrow).
* but not for Windows (I don't know how to install it).

CI for Window, I need some help to fix the cmake error (I do not have Window).

For testing CI, sign-in to https://travis-ci.org/ and https://www.appveyor.com/ with the github account and activate the zipper project from your account logo button.

**Comment by sebastiandev** [comment]
@Lecrapouille im a bit late on this.. but I've merged those changes, and CI status are displayed in the readme now.
The windows ci is failing, and im not really a windows guy right now, so if anyone wants to help there, it would be great!
Im creating a new release with the latest changes!

**Comment by Lecrapouille** [comment]
@sebastiandev No worries for the delay. In my 1st comment on this post and in other issues I posted (https://github.com/sebastiandev/zipper/issues/20) I was explaining I had problems compiling your project on Windows (I do not have Windows so just compiling from CI but in blind). When making this PR, I was secretly expecting you'll know how to fix it, fixing in the same way my CI for my project :)

**Comment by Lecrapouille** [comment]
PS: I just noticed that in .travis.yml I wrote ubuntu:16.04 instead of ubuntu:17.04

**Comment by sebastiandev** [comment]
@Lecrapouille ahah unfortunately I'm haven't been doing any c++ for quite some time, that's why this repo got a bit abandoned, but since there still seems to be people that find it useful, I'd like to keep it alive and find someone that is currently working with c++ to take ownership.

**Comment by Lecrapouille** [comment]
@sebastiandev I'm working with C++, if you want I may try to help you concerning some reported issues when I'll work again on zipped files concerning my project which will use your lib.

**Comment by sebastiandev** [comment]
@Lecrapouille that would be awesome, looks like a lot of people are using it and it would be a pity if it doesn't get proper maintenance. I've just added you as a collaborator.

**Pull request merged**
