### PR TITLE
Add name change for UNIX only

### PR DESCRIPTION
**Pull request by Togtja**
`staticZipper` will only change the name to `Zipper` on Unix system, and be differently named on Windows
To allow the building of Shared and Static Zipper

### CODE REVIEW

**Comment by Lecrapouille** [comment]
@Togtja Have you worked back on this PR ?

**Comment by Togtja** [comment]
@Lecrapouille Is anything wrong with this?
It makes the static and shared library the same on Unix (zipper.a and zipper.so) and on Windows it should be different (zipper.lib and staticZipper.lib)

**Comment by Lecrapouille** [comment]
@Togtja old post so I do not remember well the goal of this PR. I remember that I did not like `staticZipper.a` since this is not respecting Unix name. Should be `Zipper.a Zipper.so Zipper.dylib Zipper.dll`

**Comment by Togtja** [comment]
Again, the name change will ONLY happend on windows,
```
On Windows you should probably give each library a different name, since there is a ".lib" file for both shared and static. But on Linux and Mac you can even give both libraries the same name (e.g. libMyLib.a and libMyLib.so):
```
https://stackoverflow.com/questions/2152077/is-it-possible-to-get-cmake-to-build-both-a-static-and-shared-version-of-the-sam

**Comment by Togtja** [comment]
Ahh I see the confusion, I wrongly named the PR. Should be named Add name change for Windows only, my fault.
But the change essentially [this line](https://github.com/sebastiandev/zipper/blob/ecc60f44694dd91a337f64ba1114efa972a00e6b/CMakeLists.txt#L336) get placed insdie a "if not win". Where it normally would always be triggered.

**Comment by Lecrapouille** [comment]
Ok when reading `On Windows you should probably give each library a different name, since there is a ".lib" file for both shared and static.` I almost get the point :D but when reading `I prefer to use different names because that makes it easier to choose static vs. dynamic linkage on the compile line for tools that link to the library` yes and no ... Linux selects first the `.so` file then if not present will select the `.a` file. Indeed .a are juts an archive of .o files which make the binary larger than .so with weak symbols.

With `pkg-config`, if I'm right, you can pass the `--static` param.
```
echo `pkg-config --libs --static glfw3` 
-lglfw -lrt -lm -ldl
```

Vs:
```
 echo `pkg-config --libs glfw3` 
-lglfw
```

Where:
```
 cat /usr/lib/x86_64-linux-gnu/pkgconfig/glfw3.pc
prefix=/usr
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib/x86_64-linux-gnu

Name: GLFW
Description: A multi-platform library for OpenGL, window and input
Version: 3.2.1
URL: http://www.glfw.org/
Libs: -L${libdir} -lglfw
Libs.private:  -lrt -lm -ldl
Cflags: -I${includedir}
```
And if I'm right: `Libs.private` => static. Our pkg-config does not implement that, but I can change it.

**Comment by Togtja** [comment]
As it stands now you can't compile both on windows, as you get the issues in #63
I am not saying to change to name on UNIX

**Pull request merged**
